#!/bin/bash

./emu86 -w 0xf0000 -f ../mon86/mon86.bin -x 0xf000:0x0 &

sleep 1

./pcat `cat emu86.pts` <../mon86/test-mon86-in.txt >test-mon86-out.txt

diff test-mon86-out.txt ../mon86/test-mon86-ref.txt
