static char *errorstring[] =
{
	"# in a macro: not preprocessed",
	"already declared",
	"array of functions is illegal",
	"bad address",
	"bad case label",
	"bad character constant",
	"bad character",
	"bad control",
	"bad default label",
	"bad expression",
	"bad file name",
	"bad indirection count",
	"bad initializer address",
	"bad register store",
	"call of non-function",
	"can't continue in switch",
	"can't index",
	"can't load char to index reg",
	"can't open",
	"can't open input",
	"can't open output",
	"case can't be reached with char switch",
	"constant expression expected",
	"else without if",
	"end of file in #asm",
	"end of file in #define",
	"end of file in comment",
	"end of file in failed #if",
	"end of file in macro parameter expansion",
	"end of file in string constant",
	"end of line in string constant",
	"endif without if",
	"function returning array is illegal",
	"function returning function is illegal",
	"function returning structure is illegal",
	"if stack overflow",
	"illegal indirection",
	"illegal macro name",
	"illegal non-external function",
	"illegal symbol name",
	"illegal type conversion",
	"illegal type name",
	"initializer too complicated",
	"input error",
	"load of long constants not implemented",
	"loading direct long with offset not implemented",
	"local symbol table overflow",
	"macro stack overflow",
	"missing '('",
	"missing while at end of do-while",
	"need '",
	"need int or char",
	"need lvalue",
	"need scalar or ptr type",
	"need structure",
	"no active fors, switches or whiles",
	"not in a compound statement",
	"null dimension",
	"out of index registers",
	"redefined macro",
	"repeated argument",
	"repeated default label",
	"repeated parameter",
	"table full",
	"too few macro parameters",
	"too many active whiles",
	"too many cases",
	"too many macro parameters",
	"too many open compound statements",
	"too many parameters",
	"undeclared variable",
	"undefined structure element",
	"undefined structure",
	"unsigned ints only",
	"variable not in argument list"
};
