#!/bin/bash

# Call a far procedure

# arg1: segment hexadecimal
# arg2: offset in hexadecimal

if [ $# != 2 ]
	then
	echo "usage: $0 segment offset (hex)"
	else
	sudo ./mon86-host -t /dev/ttyUSB0 -s $1 -o $2 -x
	fi
