# needs dev86/bcc for building

all:
	bcc -Md -ansi -0 -O -V -W -o ./BIN/argtest.com argtest.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/bzero.com bzero.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/random.com rand.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/strlcat.com strlcat.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/strlcpy.com strlcpy.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/strlwr.com strlwr.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/strnset.com strnset.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/strrev.com strrev.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/strset.com strset.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/strupr.com strupr.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/swab.com swab.c
	bcc -Md -ansi -0 -O -V -W -o ./BIN/system.com system.c
